
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Audio : Luban.BeanBase
{
    public Audio(ByteBuf _buf) 
    {
        EnterBtn = _buf.ReadString();
        ClickBtn = _buf.ReadString();
    }

    public static Audio DeserializeAudio(ByteBuf _buf)
    {
        return new Audio(_buf);
    }

    /// <summary>
    /// 按钮悬停
    /// </summary>
    public readonly string EnterBtn;
    /// <summary>
    /// 按钮点击
    /// </summary>
    public readonly string ClickBtn;
   
    public const int __ID__ = 63613878;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "enterBtn:" + EnterBtn + ","
        + "clickBtn:" + ClickBtn + ","
        + "}";
    }
}

}
