
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Audio : Luban.BeanBase
{
    public Audio(JSONNode _buf) 
    {
        { if(!_buf["enter_btn"].IsString) { throw new SerializationException(); }  EnterBtn = _buf["enter_btn"]; }
        { if(!_buf["click_btn"].IsString) { throw new SerializationException(); }  ClickBtn = _buf["click_btn"]; }
        { if(!_buf["main_menu_bgm"].IsString) { throw new SerializationException(); }  MainMenuBgm = _buf["main_menu_bgm"]; }
        { if(!_buf["game_bgm"].IsString) { throw new SerializationException(); }  GameBgm = _buf["game_bgm"]; }
    }

    public static Audio DeserializeAudio(JSONNode _buf)
    {
        return new Audio(_buf);
    }

    /// <summary>
    /// 按钮悬停
    /// </summary>
    public readonly string EnterBtn;
    /// <summary>
    /// 按钮点击
    /// </summary>
    public readonly string ClickBtn;
    /// <summary>
    /// 主菜单背景乐
    /// </summary>
    public readonly string MainMenuBgm;
    /// <summary>
    /// 游戏背景乐
    /// </summary>
    public readonly string GameBgm;
   
    public const int __ID__ = 63613878;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "enterBtn:" + EnterBtn + ","
        + "clickBtn:" + ClickBtn + ","
        + "mainMenuBgm:" + MainMenuBgm + ","
        + "gameBgm:" + GameBgm + ","
        + "}";
    }
}

}
