
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class L10nTest : Luban.BeanBase
{
    public L10nTest(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["des"].IsString) { throw new SerializationException(); }  Des = _buf["des"]; }
        Des_Ref = null;
    }

    public static L10nTest DeserializeL10nTest(JSONNode _buf)
    {
        return new L10nTest(_buf);
    }

    public readonly int Id;
    public readonly string Des;
    public L10nGame Des_Ref;
   
    public const int __ID__ = 1325996437;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        Des_Ref = tables.TbL10nGame.GetOrDefault(Des);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "des:" + Des + ","
        + "}";
    }
}

}
