
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class L10nGame : Luban.BeanBase
{
    public L10nGame(ByteBuf _buf) 
    {
        L10nKey = _buf.ReadString();
        Cn = _buf.ReadString();
        En = _buf.ReadString();
    }

    public static L10nGame DeserializeL10nGame(ByteBuf _buf)
    {
        return new L10nGame(_buf);
    }

    /// <summary>
    /// 语言key
    /// </summary>
    public readonly string L10nKey;
    /// <summary>
    /// 中文
    /// </summary>
    public readonly string Cn;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string En;
   
    public const int __ID__ = 1325605109;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "l10nKey:" + L10nKey + ","
        + "cn:" + Cn + ","
        + "en:" + En + ","
        + "}";
    }
}

}

