
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class Tbl10nTest
{
    private readonly System.Collections.Generic.Dictionary<int, L10nTest> _dataMap;
    private readonly System.Collections.Generic.List<L10nTest> _dataList;
    
    public Tbl10nTest(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, L10nTest>();
        _dataList = new System.Collections.Generic.List<L10nTest>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            L10nTest _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = L10nTest.DeserializeL10nTest(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, L10nTest> DataMap => _dataMap;
    public System.Collections.Generic.List<L10nTest> DataList => _dataList;

    public L10nTest GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public L10nTest Get(int key) => _dataMap[key];
    public L10nTest this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

